{{- if and .Values.connection.password (not .Values.connection.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arango-tools.secretName" . }}
  labels:
    {{- include "arango-tools.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.connection.passwordKey }}: {{ .Values.connection.password | quote }}
{{- end }}
